#邮箱配置
spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: henry.vu.32698.001@gmail.com
    password: zuvm tpbx clmw slof
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
alarm:
  # 接收报警的用户邮箱，多个人时，使用英文逗号分隔
  user: henry.vu.32698.001@gmail.com